<div style="border-left: 6px solid #00356B; padding-left: 15px; margin-bottom: 20px;">
  <h1 style="margin-bottom: 5px; color: #00356B"><strong>Assignment 3:</strong> Part 3 (Cross-Model Competition)</h1>
  <span style="font-size: 1.2em; color: #444; font-weight: bold">S&DS 5350 | Social Algorithms</span>
  <br><br>
  <strong>Primary:</strong> Cailey Bobadilla (cjb239)
  <br>
  <strong>Partner :</strong> Brandon Tran (bat53)
  <br>
  <strong>Group:</strong> 9
</div>

---

*Mood for this part:*

<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/5Ds3yH73nMHgkmJxcxqPrr?utm_source=generator" width="40%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

#### AI Acknowledgement

I used Claude Sonnet 4.6 to develop this Jupyter notebook. My main use was implementing my logic for the additional components in the `analyze_crossplay()` function.

Now evaluate the role of diversity across player models.

#### III.1 Local model set

Use at least 3 different local models. Run pairwise 2-player competitions for your chosen local models.

1. Generate one answer file per player/model. Use the same prompt and temperature settings across the models (optional: explore variations in prompt/temperature).
2. Judge each matchup by passing the relevant files to `judge.py`.
3. Use the returned CSV scores for analysis.

##### Head of the Answers for All Models (Self-Play) at Temperature = 0.9

In [141]:
import pandas as pd

`qwen2.5:7b`

In [142]:
# Read in CSV files for player 1 and player 2 at temperature=0.9
df_qwen_default_p1 = pd.read_csv("part3_selfplay_outputs/self_default_09_qwen_Player_1.csv")
df_qwen_default_p2 = pd.read_csv("part3_selfplay_outputs/self_default_09_qwen_Player_2.csv")

In [143]:
# Display the head of the answers for player 1 at temperature=0.9
df_qwen_default_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Albatross,qwen2.5:7b,qwen_Player_1_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Alpaca,qwen2.5:7b,qwen_Player_1_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Alpaca,qwen2.5:7b,qwen_Player_1_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Alpaca,qwen2.5:7b,qwen_Player_1_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Albatross,qwen2.5:7b,qwen_Player_1_default_09,0.9,40,baseline

In [144]:
# Display the head of the answers for player 2 at temperature=0.9
df_qwen_default_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Antelope,qwen2.5:7b,qwen_Player_2_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Alligator,qwen2.5:7b,qwen_Player_2_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Alpaca,qwen2.5:7b,qwen_Player_2_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Alpaca,qwen2.5:7b,qwen_Player_2_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Albatross,qwen2.5:7b,qwen_Player_2_default_09,0.9,40,baseline

`llama3.2:3b`

In [145]:
# Read in CSV files for player 1 and player 2 at temperature=0.9
df_llama_default_p1 = pd.read_csv("part3_selfplay_outputs/self_default_09_llama_Player_1.csv")
df_llama_default_p2 = pd.read_csv("part3_selfplay_outputs/self_default_09_llama_Player_2.csv")

In [146]:
# Display the head of the answers for player 1 at temperature=0.9
df_llama_default_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,llama3.2:3b,llama_Player_1_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Aardvark,llama3.2:3b,llama_Player_1_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Aardvark,llama3.2:3b,llama_Player_1_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Aardvark,llama3.2:3b,llama_Player_1_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Aardvark,llama3.2:3b,llama_Player_1_default_09,0.9,40,baseline

In [147]:
# Display the head of the answers for player 2 at temperature=0.9
df_llama_default_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,llama3.2:3b,llama_Player_2_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Aardvark,llama3.2:3b,llama_Player_2_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Aardvark,llama3.2:3b,llama_Player_2_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Aardvark,llama3.2:3b,llama_Player_2_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Aardvark,llama3.2:3b,llama_Player_2_default_09,0.9,40,baseline

`gemma2:2b`

In [148]:
# Read in CSV files for player 1 and player 2 at temperature=0.9
df_gemma_default_p1 = pd.read_csv("part3_selfplay_outputs/self_default_09_gemma_Player_1.csv")
df_gemma_default_p2 = pd.read_csv("part3_selfplay_outputs/self_default_09_gemma_Player_2.csv")

In [149]:
# Display the head of the answers for player 1 at temperature=0.9
df_gemma_default_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Alligator,gemma2:2b,gemma_Player_1_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Alpaca,gemma2:2b,gemma_Player_1_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Aardvark,gemma2:2b,gemma_Player_1_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Alpaca,gemma2:2b,gemma_Player_1_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Antelope,gemma2:2b,gemma_Player_1_default_09,0.9,40,baseline

In [150]:
# Display the head of the answers for player 2 at temperature=0.9
df_gemma_default_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Armadillo,gemma2:2b,gemma_Player_2_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Alpaca,gemma2:2b,gemma_Player_2_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Alpaca,gemma2:2b,gemma_Player_2_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Alpaca,gemma2:2b,gemma_Player_2_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Antelope,gemma2:2b,gemma_Player_2_default_09,0.9,40,baseline

##### Head of the Answers for All Models (Self-Play) at Temperature = 2.0

`qwen2.5:7b`

In [151]:
# Read in CSV files for player 1 and player 2 at temperature=2.0
df_qwen_opt_p1 = pd.read_csv("part3_selfplay_outputs/self_opt_20_qwen_Player_1.csv")
df_qwen_opt_p2 = pd.read_csv("part3_selfplay_outputs/self_opt_20_qwen_Player_2.csv")

In [152]:
# Display the head of the answers for player 1 at temperature=2.0
df_qwen_opt_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Albatross,qwen2.5:7b,qwen_Player_1_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Alpaca,qwen2.5:7b,qwen_Player_1_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Antelope,qwen2.5:7b,qwen_Player_1_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Antelope,qwen2.5:7b,qwen_Player_1_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Albatross,qwen2.5:7b,qwen_Player_1_opt_20,2.0,40,baseline

In [153]:
# Display the head of the answers for player 2 at temperature=2.0
df_qwen_opt_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Alligator,qwen2.5:7b,qwen_Player_2_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Alligator,qwen2.5:7b,qwen_Player_2_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Antelope,qwen2.5:7b,qwen_Player_2_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Alpaca,qwen2.5:7b,qwen_Player_2_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Alligator,qwen2.5:7b,qwen_Player_2_opt_20,2.0,40,baseline

`llama3.2:3b`

In [154]:
# Read in CSV files for player 1 and player 2 at temperature=2.0
df_llama_opt_p1 = pd.read_csv("part3_selfplay_outputs/self_opt_20_llama_Player_1.csv")
df_llama_opt_p2 = pd.read_csv("part3_selfplay_outputs/self_opt_20_llama_Player_2.csv")

In [155]:
# Display the head of the answers for player 1 at temperature=2.0
df_llama_opt_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,llama3.2:3b,llama_Player_1_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,llama3.2:3b,llama_Player_1_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Aardvark,llama3.2:3b,llama_Player_1_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Aardvark,llama3.2:3b,llama_Player_1_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Aardvark,llama3.2:3b,llama_Player_1_opt_20,2.0,40,baseline

In [156]:
# Display the head of the answers for player 2 at temperature=2.0
df_llama_opt_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,llama3.2:3b,llama_Player_2_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Alligator,llama3.2:3b,llama_Player_2_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Alligator,llama3.2:3b,llama_Player_2_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Aardvark,llama3.2:3b,llama_Player_2_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Aardvark,llama3.2:3b,llama_Player_2_opt_20,2.0,40,baseline

`gemma2:2b`

In [157]:
# Read in CSV files for player 1 and player 2 at temperature=2.0
df_gemma_opt_p1 = pd.read_csv("part3_selfplay_outputs/self_opt_20_gemma_Player_1.csv")
df_gemma_opt_p2 = pd.read_csv("part3_selfplay_outputs/self_opt_20_gemma_Player_2.csv")

In [158]:
# Display the head of the answers for player 1 at temperature=2.0
df_gemma_opt_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,gemma2:2b,gemma_Player_1_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Anteater,gemma2:2b,gemma_Player_1_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Albatross,gemma2:2b,gemma_Player_1_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Ants,gemma2:2b,gemma_Player_1_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Armadillo,gemma2:2b,gemma_Player_1_opt_20,2.0,40,baseline

In [159]:
# Display the head of the answers for player 2 at temperature=2.0
df_gemma_opt_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Ape,gemma2:2b,gemma_Player_2_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,gemma2:2b,gemma_Player_2_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Alpaca,gemma2:2b,gemma_Player_2_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Alpaca,gemma2:2b,gemma_Player_2_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Alligator,gemma2:2b,gemma_Player_2_opt_20,2.0,40,baseline

##### Head of the Answers for All Models (Self-Play) Using the Obscure Prompt (Temperature = 2.0)

`qwen2.5:7b`

In [160]:
# Read in CSV files for player 1 and player 2 for the obscure prompt 
# (temperature=2.0)
df_qwen_obscure_p1 = pd.read_csv("part3_selfplay_outputs/self_obscure_20_qwen_Player_1_Obscure.csv")
df_qwen_obscure_p2 = pd.read_csv("part3_selfplay_outputs/self_obscure_20_qwen_Player_2_Obscure.csv")

In [161]:
# Display the head of the answers for player 1 for the obscure prompt
df_qwen_obscure_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Axolotl,qwen2.5:7b,qwen_Player_1_Obscure_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Axolotl,qwen2.5:7b,qwen_Player_1_Obscure_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Albino Alligator Snake,qwen2.5:7b,qwen_Player_1_Obscure_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Aardvark,qwen2.5:7b,qwen_Player_1_Obscure_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Axolotl,qwen2.5:7b,qwen_Player_1_Obscure_obscure_20,2.0,40,baseline

In [162]:
# Display the head of the answers for player 2 for the obscure prompt
df_qwen_obscure_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,qwen2.5:7b,qwen_Player_2_Obscure_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,qwen2.5:7b,qwen_Player_2_Obscure_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Aardvark,qwen2.5:7b,qwen_Player_2_Obscure_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Aardvark,qwen2.5:7b,qwen_Player_2_Obscure_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Albino anteater,qwen2.5:7b,qwen_Player_2_Obscure_obscure_20,2.0,40,baseline

`llama3.2:3b`

In [163]:
# Read in CSV files for player 1 and player 2 for the obscure prompt 
# (temperature=2.0)
df_llama_obscure_p1 = pd.read_csv("part3_selfplay_outputs/self_obscure_20_llama_Player_1_Obscure.csv")
df_llama_obscure_p2 = pd.read_csv("part3_selfplay_outputs/self_obscure_20_llama_Player_2_Obscure.csv")

In [164]:
# Display the head of the answers for player 1 for the obscure prompt
df_llama_obscure_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Axolotl,llama3.2:3b,llama_Player_1_Obscure_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Ailurus,llama3.2:3b,llama_Player_1_Obscure_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Ailuravictis,llama3.2:3b,llama_Player_1_Obscure_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Aye-Aye,llama3.2:3b,llama_Player_1_Obscure_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Ailurus fulgens,llama3.2:3b,llama_Player_1_Obscure_obscure_20,2.0,40,baseline

In [165]:
# Display the head of the answers for player 2 for the obscure prompt
df_llama_obscure_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Ailuravireola,llama3.2:3b,llama_Player_2_Obscure_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Aye-Aye,llama3.2:3b,llama_Player_2_Obscure_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Aye-Aye,llama3.2:3b,llama_Player_2_Obscure_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Ailuravidae,llama3.2:3b,llama_Player_2_Obscure_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Axolotl,llama3.2:3b,llama_Player_2_Obscure_obscure_20,2.0,40,baseline

`gemma2:2b`

In [166]:
# Read in CSV files for player 1 and player 2 for the obscure prompt 
# (temperature=2.0)
df_gemma_obscure_p1 = pd.read_csv("part3_selfplay_outputs/self_obscure_20_gemma_Player_1_Obscure.csv")
df_gemma_obscure_p2 = pd.read_csv("part3_selfplay_outputs/self_obscure_20_gemma_Player_2_Obscure.csv")

In [167]:
# Display the head of the answers for player 1 for the obscure prompt
df_gemma_obscure_p1.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aligatorfish,gemma2:2b,gemma_Player_1_Obscure_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Aye-aye,gemma2:2b,gemma_Player_1_Obscure_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Aardvark,gemma2:2b,gemma_Player_1_Obscure_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Affenpinscher,gemma2:2b,gemma_Player_1_Obscure_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Aardvark,gemma2:2b,gemma_Player_1_Obscure_obscure_20,2.0,40,baseline

In [168]:
# Display the head of the answers for player 2 for the obscure prompt
df_gemma_obscure_p2.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aye-aye,gemma2:2b,gemma_Player_2_Obscure_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,gemma2:2b,gemma_Player_2_Obscure_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Aye-aye,gemma2:2b,gemma_Player_2_Obscure_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Aye-aye,gemma2:2b,gemma_Player_2_Obscure_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Aye-aye,gemma2:2b,gemma_Player_2_Obscure_obscure_20,2.0,40,baseline

##### Head of the Answers for `qwen2.5:7b` vs. `llama3.2:3b` vs. `gemma2:2b` at Temperature = 0.9

In [169]:
# Read in CSV files for cross-play at temperature=0.9
df_qwen_crossplay_default = pd.read_csv("part3_crossplay_outputs/default_09_qwen.csv")
df_llama_crossplay_default = pd.read_csv("part3_crossplay_outputs/default_09_llama.csv")
df_gemma_crossplay_default = pd.read_csv("part3_crossplay_outputs/default_09_gemma.csv")

In [170]:
# Display the head of answers for qwen at temperature=0.9
df_qwen_crossplay_default.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Antelope,qwen2.5:7b,qwen_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Alpaca,qwen2.5:7b,qwen_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Alpaca,qwen2.5:7b,qwen_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Antelope,qwen2.5:7b,qwen_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Alpaca,qwen2.5:7b,qwen_default_09,0.9,40,baseline

In [171]:
# Display the head of answers for llama at temperature=0.9
df_llama_crossplay_default.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Alligator,llama3.2:3b,llama_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Aardvark,llama3.2:3b,llama_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Alligator,llama3.2:3b,llama_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Alligator,llama3.2:3b,llama_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Aardvark,llama3.2:3b,llama_default_09,0.9,40,baseline

In [172]:
# Display the head of answers for gemma at temperature=0.9
df_gemma_crossplay_default.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,gemma2:2b,gemma_default_09,0.9,40,baseline
1,Q001,A,Animals,1,Alligator,gemma2:2b,gemma_default_09,0.9,40,baseline
2,Q001,A,Animals,2,Alligator,gemma2:2b,gemma_default_09,0.9,40,baseline
3,Q001,A,Animals,3,Ape,gemma2:2b,gemma_default_09,0.9,40,baseline
4,Q001,A,Animals,4,Ant,gemma2:2b,gemma_default_09,0.9,40,baseline

##### Head of the Answers for `qwen2.5:7b` vs. `llama3.2:3b` vs. `gemma2:2b` at Temperature = 2.0

In [173]:
# Read in CSV files for cross-play at temperature=2.0
df_qwen_crossplay_opt = pd.read_csv("part3_crossplay_outputs/opt_20_qwen.csv")
df_llama_crossplay_opt = pd.read_csv("part3_crossplay_outputs/opt_20_llama.csv")
df_gemma_crossplay_opt = pd.read_csv("part3_crossplay_outputs/opt_20_gemma.csv")

In [174]:
# Display the head of answers for qwen at temperature=2.0
df_qwen_crossplay_opt.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Alligator,qwen2.5:7b,qwen_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Antelope,qwen2.5:7b,qwen_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Alpaca,qwen2.5:7b,qwen_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Alpaca,qwen2.5:7b,qwen_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Antelope,qwen2.5:7b,qwen_opt_20,2.0,40,baseline

In [175]:
# Display the head of answers for llama at temperature=2.0
df_llama_crossplay_opt.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Alligator,llama3.2:3b,llama_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,llama3.2:3b,llama_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Aardvark,llama3.2:3b,llama_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Aardvark,llama3.2:3b,llama_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Aardvark,llama3.2:3b,llama_opt_20,2.0,40,baseline

In [176]:
# Display the head of answers for gemma at temperature=2.0
df_gemma_crossplay_opt.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,gemma2:2b,gemma_opt_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,gemma2:2b,gemma_opt_20,2.0,40,baseline
2,Q001,A,Animals,2,Alpaca,gemma2:2b,gemma_opt_20,2.0,40,baseline
3,Q001,A,Animals,3,Alligator,gemma2:2b,gemma_opt_20,2.0,40,baseline
4,Q001,A,Animals,4,Ape,gemma2:2b,gemma_opt_20,2.0,40,baseline

##### Head of the Answers for `qwen2.5:7b` vs. `llama3.2:3b` vs. `gemma2:2b` Using the Obscure Prompt (Temperature = 2.0)

In [177]:
# Read in CSV files for cross-play for the obscure prompt (temperature=2.0)
df_qwen_crossplay_obscure = pd.read_csv("part3_crossplay_outputs/obscure_20_qwen.csv")
df_llama_crossplay_obscure = pd.read_csv("part3_crossplay_outputs/obscure_20_llama.csv")
df_gemma_crossplay_obscure = pd.read_csv("part3_crossplay_outputs/obscure_20_gemma.csv")

In [178]:
# Display the head of answers for qwen for the obscure prompt
df_qwen_crossplay_obscure.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Albatross,qwen2.5:7b,qwen_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Aardvark,qwen2.5:7b,qwen_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Alakazanga,qwen2.5:7b,qwen_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Aardvark,qwen2.5:7b,qwen_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Axolotl,qwen2.5:7b,qwen_obscure_20,2.0,40,baseline

In [179]:
# Display the head of answers for llama for the obscure prompt
df_llama_crossplay_obscure.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Axolotl,llama3.2:3b,llama_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Acanthostega,llama3.2:3b,llama_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Ailurus fulgens,llama3.2:3b,llama_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Ailuravidae,llama3.2:3b,llama_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Acanthocyon,llama3.2:3b,llama_obscure_20,2.0,40,baseline

In [180]:
# Display the head of answers for gemma for the obscure prompt
df_gemma_crossplay_obscure.head()

,question_id,letter,category,round_idx,answer,model,player_id,temperature,top_k,prompt_id
0,Q001,A,Animals,0,Aardvark,gemma2:2b,gemma_obscure_20,2.0,40,baseline
1,Q001,A,Animals,1,Aakashis,gemma2:2b,gemma_obscure_20,2.0,40,baseline
2,Q001,A,Animals,2,Aok,gemma2:2b,gemma_obscure_20,2.0,40,baseline
3,Q001,A,Animals,3,Aepycamel,gemma2:2b,gemma_obscure_20,2.0,40,baseline
4,Q001,A,Animals,4,Aye-aye,gemma2:2b,gemma_obscure_20,2.0,40,baseline

#### III.2 Analysis

Compare self-play for each local model and cross-play for each pair of local models.

Report at least:
- Average score per player against each opponent
- Validity rates for each model

Discuss what it means for models to do differently well against themselves than they do against other models, and the role of temperature in that behavior. Hint: what happens when a low temperature model plays against itself?

##### Game Analysis Function for Self-Play

In [181]:
# From Part 2 jupyter notebook
def analyze_selfplay(df, game_name):
    """
    Calculates the overall validity and overall average score per player in a 
    game. Also, retrieves the top 3 hardest and easiest categories, and 
    calculates their average points and validity.

    Args:
        df (pd.DataFrame): Contains judged rows from the scattergories game.
        game_name (str): Name of the game.
    """
    print(f"\nOVERALL OUTCOMES: {game_name}")

    # Calculate the overall validity and average score
    overall_validity = df['valid'].mean()
    overall_score = df['score'].mean()

    # Print the overall validity and average score
    print(f"Overall Validity Rate: {overall_validity:.1%}")
    print(
        f"Overall Average Score per Player: {overall_score:.1%} points per "
        "answer"
    )

    # Caclulate metrics for each question
    # NOTE: This is done by grouping by the question features and calculating
    # the mean for valid and score
    per_question = (
        df.groupby(['question_id', 'letter', 'category'])
        [['valid', 'score']]
        .mean()
        .reset_index()
    )

    # Get the 3 hardest and 3 easiest questions
    hardest = per_question.sort_values(by='score').head(3)
    easiest = per_question.sort_values(by='score', ascending=False).head(3)

    print("\nTop 3 Hardest Categories (Lowest Score):")

    # Iterate through each row in the hardest questions/categories
    for _, row in hardest.iterrows():
        # Print the letter and category, and their average points and validity
        print(
            f"Letter {row['letter']} - {row['category']}: {row['score']:.2f} "
            f"average points (Validity: {row['valid']:.1%})"
        )

    print("\nTop 3 Easiest Categories (Highest Score):")

    # Iterate through each row in the easiest questions/categories
    for _, row in easiest.iterrows():
        # Print the letter and category, and their average points and validity
        print(
            f"Letter {row['letter']} - {row['category']}: {row['score']:.2f} "
            f"average points (Validity: {row['valid']:.1%})"
        )

##### Game Analysis for All Self-Play Scenarios

In [182]:
import pandas as pd

`qwen2.5:7b`

In [183]:
# Read in CSV files for qwen judged self-play
df_judged_self_qwen_default = pd.read_csv("part3_judged_outputs/judged_self_qwen_default_09.csv")
df_judged_self_qwen_opt = pd.read_csv("part3_judged_outputs/judged_self_qwen_opt_20.csv")
df_judged_self_qwen_obscure = pd.read_csv("part3_judged_outputs/judged_self_qwen_obscure_20.csv")

# Analyze the games from qwen self-play
analyze_selfplay(df_judged_self_qwen_default, "Qwen Self-Play (original prompt, temperature=0.9)")
analyze_selfplay(df_judged_self_qwen_opt, "Qwen Self-Play (original prompt, temperature=2.0)")
analyze_selfplay(df_judged_self_qwen_obscure, "Qwen Self-Play (obscure prompt, temperature=2.0)")

OVERALL OUTCOMES: Qwen Self-Play (original prompt, temperature=0.9)
Overall Validity Rate: 77.3%
Overall Average Score per Player: 34.2% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter L - Things in a library: 0.00 average points (Validity: 0.0%)
Letter Q - Fictional characters: 0.00 average points (Validity: 100.0%)
Letter I - Cities: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 1.00 average points (Validity: 100.0%)
Letter G - Things in a toolbox: 1.00 average points (Validity: 100.0%)
Letter N - Birds: 0.90 average points (Validity: 90.0%)

OVERALL OUTCOMES: Qwen Self-Play (original prompt, temperature=2.0)
Overall Validity Rate: 76.2%
Overall Average Score per Player: 39.7% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter I - Cities: 0.00 average points (Validity: 0.0%)
Letter N - Things in a hospital: 0.00 average points (Validity: 100.0%)
Letter M - Languages: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter B - Things that are red: 1.00 average points (Validity: 100.0%)
Letter J - Things in a refrigerator: 1.00 average points (Validity: 100.0%)
Letter D - Plants: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Qwen Self-Play (obscure prompt, temperature=2.0)
Overall Validity Rate: 35.9%
Overall Average Score per Player: 28.7% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter E - Companies: 0.00 average points (Validity: 0.0%)
Letter Z - Animals: 0.00 average points (Validity: 100.0%)
Letter A - Things in a kitchen: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter X - Words in English: 1.00 average points (Validity: 100.0%)
Letter K - Things in a grocery store: 1.00 average points (Validity: 100.0%)
Letter Q - Words in English: 0.80 average points (Validity: 80.0%)

`llama3.2:3b`

In [184]:
# Read in CSV files for llama judged self-play
df_judged_self_llama_default = pd.read_csv("part3_judged_outputs/judged_self_llama_default_09.csv")
df_judged_self_llama_opt = pd.read_csv("part3_judged_outputs/judged_self_llama_opt_20.csv")
df_judged_self_llama_obscure = pd.read_csv("part3_judged_outputs/judged_self_llama_obscure_20.csv")

# Analyze the games from llama self-play
analyze_selfplay(df_judged_self_llama_default, "Llama Self-Play (original prompt, temperature=0.9)")
analyze_selfplay(df_judged_self_llama_opt, "Llama Self-Play (original prompt, temperature=2.0)")
analyze_selfplay(df_judged_self_llama_obscure, "Llama Self-Play (obscure prompt, temperature=2.0)")

OVERALL OUTCOMES: Llama Self-Play (original prompt, temperature=0.9)
Overall Validity Rate: 83.3%
Overall Average Score per Player: 38.0% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter A - Animals: 0.00 average points (Validity: 100.0%)
Letter N - Birds: 0.00 average points (Validity: 100.0%)
Letter L - Books: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter B - Fruits: 1.00 average points (Validity: 100.0%)
Letter J - Things in a refrigerator: 1.00 average points (Validity: 100.0%)
Letter H - Countries: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Llama Self-Play (original prompt, temperature=2.0)
Overall Validity Rate: 82.2%
Overall Average Score per Player: 52.5% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter V - Things you wear: 0.00 average points (Validity: 100.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)
Letter F - Fish: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 1.00 average points (Validity: 100.0%)
Letter C - Desserts: 1.00 average points (Validity: 100.0%)
Letter S - Animals: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Llama Self-Play (obscure prompt, temperature=2.0)
Overall Validity Rate: 37.5%
Overall Average Score per Player: 31.2% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)
Letter R - Songs: 0.00 average points (Validity: 0.0%)
Letter K - Superheroes: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter G - Foods: 0.90 average points (Validity: 90.0%)
Letter D - Plants: 0.80 average points (Validity: 80.0%)
Letter Y - Foods: 0.80 average points (Validity: 80.0%)

`gemma2:2b`

In [185]:
# Read in CSV files for gemma judged self-play
df_judged_self_gemma_default = pd.read_csv("part3_judged_outputs/judged_self_gemma_default_09.csv")
df_judged_self_gemma_opt = pd.read_csv("part3_judged_outputs/judged_self_gemma_opt_20.csv")
df_judged_self_gemma_obscure = pd.read_csv("part3_judged_outputs/judged_self_gemma_obscure_20.csv")

# Analyze the games from gemma self-play
analyze_selfplay(df_judged_self_gemma_default, "Gemma Self-Play (original prompt, temperature=0.9)")
analyze_selfplay(df_judged_self_gemma_opt, "Gemma Self-Play (original prompt, temperature=2.0)")
analyze_selfplay(df_judged_self_gemma_obscure, "Gemma Self-Play (obscure prompt, temperature=2.0)")

OVERALL OUTCOMES: Gemma Self-Play (original prompt, temperature=0.9)
Overall Validity Rate: 74.7%
Overall Average Score per Player: 48.8% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter I - Musical artists: 0.00 average points (Validity: 0.0%)
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter E - Companies: 1.00 average points (Validity: 100.0%)
Letter C - Countries: 1.00 average points (Validity: 100.0%)
Letter M - Clothing items: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Gemma Self-Play (original prompt, temperature=2.0)
Overall Validity Rate: 73.8%
Overall Average Score per Player: 54.7% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter S - Things in an office: 0.00 average points (Validity: 100.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)
Letter B - Things that are red: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter A - Animals: 1.00 average points (Validity: 100.0%)
Letter C - Board games: 1.00 average points (Validity: 100.0%)
Letter P - Vegetables: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Gemma Self-Play (obscure prompt, temperature=2.0)
Overall Validity Rate: 35.0%
Overall Average Score per Player: 33.4% points per answer

Top 3 Hardest Categories (Lowest Score):
Letter O - Companies: 0.00 average points (Validity: 0.0%)
Letter K - Superheroes: 0.00 average points (Validity: 0.0%)
Letter C - Board games: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter Y - Foods: 1.00 average points (Validity: 100.0%)
Letter X - Words in English: 1.00 average points (Validity: 100.0%)
Letter A - Animals: 0.90 average points (Validity: 90.0%)

##### Game Analysis Function for Cross-Play

In [186]:
# Modified analyze_selfplay() function to acommmodate model comparisons
def analyze_crossplay(df, game_name):
    """
    Calculates the overall validity and overall average score in a game, as well
    as individual statistics per model/player. Also, retrieves the top 3 hardest 
    and easiest categories.

    Args:
        df (pd.DataFrame): Contains judged rows from the scattergories game.
        game_name (str): Name of the game.
    """
    print(f"\nOVERALL OUTCOMES: {game_name}")

    # Calculate the overall validity and average score
    overall_validity = df['valid'].mean()
    overall_score = df['score'].mean()

    # Print the overall validity and average score
    print(f"Overall Validity Rate: {overall_validity:.1%}")
    print(
        f"Overall Average Score per Player: {overall_score:.1%} points per "
        "answer"
    )

    # Calculate individual model/player statistics
    # NOTE: This is done by grouping by the model/player and calculating the 
    # mean for valid and score
    print("\nPer-Model Breakdown:")
    player_stats = (
        df.groupby('player_id')
        [['valid', 'score']]
        .mean()
        .reset_index()
    )

    # Iterate through each row in the player_stats dataframe to get the validity 
    # and average score for each model
    for _, row in player_stats.iterrows():
        print(
            f"Player {row['player_id']}: {row['score']:.2f} average points "
            f"(Validity: {row['valid']:.1%})"
        )

    # Calculate head-to-head scores between models
    # NOTE: This is done by grouping by player and round, and calculating the 
    # mean for valid and score
    head_to_head = (
        df.groupby(['player_id', 'round_idx'])
        [['valid', 'score']]
        .mean()
        .reset_index()
    )

    # Iterate through each row in the head_to_head dataframt to get the validity
    # and average score for each model in each round
    for _, row in head_to_head.iterrows():
        print(
            f"Player {row['player_id']} | Round {row['round_idx'] + 1}: "
            f"{row['score']:.2f} average points (Validity: {row['valid']:.1%})"
        )

    # Caclulate metrics for each question
    # NOTE: This is done by grouping by the question features and calculating
    # the mean for valid and score
    per_question = (
        df.groupby(['question_id', 'letter', 'category'])
        [['valid', 'score']]
        .mean()
        .reset_index()
    )

    # Get the 3 hardest and 3 easiest questions
    hardest = per_question.sort_values(by='score').head(3)
    easiest = per_question.sort_values(by='score', ascending=False).head(3)

    print("\nTop 3 Hardest Categories (Lowest Score):")

    # Iterate through each row in the hardest questions/categories
    for _, row in hardest.iterrows():
        # Print the letter and category, and their average points and validity
        print(
            f"Letter {row['letter']} - {row['category']}: {row['score']:.2f} "
            f"average points (Validity: {row['valid']:.1%})"
        )

    print("\nTop 3 Easiest Categories (Highest Score):")

    # Iterate through each row in the easiest questions/categories
    for _, row in easiest.iterrows():
        # Print the letter and category, and their average points and validity
        print(
            f"Letter {row['letter']} - {row['category']}: {row['score']:.2f} "
            f"average points (Validity: {row['valid']:.1%})"
        )

##### Game Analysis for All Cross-Play Scenarios

In [187]:
import pandas as pd

`qwen2.5:7b` vs. `llama3.2:3b` vs. `gemma2:2b` at Temperature = 0.9

In [188]:
# Read in CSV files for judged cross-play at temperature=0.9
df_judged_cross_qwen_vs_llama_default = pd.read_csv("part3_judged_outputs/judged_cross_qwen_vs_llama_default_09.csv")
df_judged_cross_qwen_vs_gemma_default = pd.read_csv("part3_judged_outputs/judged_cross_qwen_vs_gemma_default_09.csv")
df_judged_cross_llama_vs_gemma_default = pd.read_csv("part3_judged_outputs/judged_cross_llama_vs_gemma_default_09.csv")

# Analyze the games from cross-play at temperature=0.9
analyze_crossplay(df_judged_cross_qwen_vs_llama_default, "Qwen vs Llama (original prompt, temperature=0.9)")
analyze_crossplay(df_judged_cross_qwen_vs_gemma_default, "Qwen vs Gemma (original prompt, temperature=0.9)")
analyze_crossplay(df_judged_cross_llama_vs_gemma_default, "Llama vs Gemma (original prompt, temperature=0.9)")

OVERALL OUTCOMES: Qwen vs Llama (original prompt, temperature=0.9)
Overall Validity Rate: 78.4%
Overall Average Score per Player: 52.2% points per answer

Per-Model Breakdown:
Player default_09_llama: 0.53 average points (Validity: 79.4%)
Player default_09_qwen: 0.51 average points (Validity: 77.5%)
Player default_09_llama | Round 1: 0.55 average points (Validity: 76.6%)
Player default_09_llama | Round 2: 0.50 average points (Validity: 76.6%)
Player default_09_llama | Round 3: 0.47 average points (Validity: 79.7%)
Player default_09_llama | Round 4: 0.59 average points (Validity: 85.9%)
Player default_09_llama | Round 5: 0.55 average points (Validity: 78.1%)
Player default_09_qwen | Round 1: 0.58 average points (Validity: 79.7%)
Player default_09_qwen | Round 2: 0.52 average points (Validity: 78.1%)
Player default_09_qwen | Round 3: 0.45 average points (Validity: 78.1%)
Player default_09_qwen | Round 4: 0.50 average points (Validity: 76.6%)
Player default_09_qwen | Round 5: 0.52 average points (Validity: 75.0%)

Top 3 Hardest Categories (Lowest Score):
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)
Letter Z - Animals: 0.00 average points (Validity: 100.0%)
Letter X - Words in English: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter A - Animals: 1.00 average points (Validity: 100.0%)
Letter F - Things in a backpack: 1.00 average points (Validity: 100.0%)
Letter K - Cities: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Qwen vs Gemma (original prompt, temperature=0.9)
Overall Validity Rate: 76.1%
Overall Average Score per Player: 60.5% points per answer

Per-Model Breakdown:
Player default_09_gemma: 0.59 average points (Validity: 75.0%)
Player default_09_qwen: 0.62 average points (Validity: 77.2%)
Player default_09_gemma | Round 1: 0.55 average points (Validity: 73.4%)
Player default_09_gemma | Round 2: 0.64 average points (Validity: 75.0%)
Player default_09_gemma | Round 3: 0.59 average points (Validity: 76.6%)
Player default_09_gemma | Round 4: 0.59 average points (Validity: 75.0%)
Player default_09_gemma | Round 5: 0.59 average points (Validity: 75.0%)
Player default_09_qwen | Round 1: 0.59 average points (Validity: 78.1%)
Player default_09_qwen | Round 2: 0.66 average points (Validity: 76.6%)
Player default_09_qwen | Round 3: 0.59 average points (Validity: 76.6%)
Player default_09_qwen | Round 4: 0.62 average points (Validity: 78.1%)
Player default_09_qwen | Round 5: 0.61 average points (Validity: 76.6%)

Top 3 Hardest Categories (Lowest Score):
Letter I - Cities: 0.00 average points (Validity: 0.0%)
Letter E - Sports: 0.00 average points (Validity: 100.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter A - Animals: 1.00 average points (Validity: 100.0%)
Letter D - Musical instruments: 1.00 average points (Validity: 100.0%)
Letter P - Historical figures: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Llama vs Gemma (original prompt, temperature=0.9)
Overall Validity Rate: 76.1%
Overall Average Score per Player: 57.0% points per answer

Per-Model Breakdown:
Player default_09_gemma: 0.55 average points (Validity: 73.8%)
Player default_09_llama: 0.59 average points (Validity: 78.4%)
Player default_09_gemma | Round 1: 0.55 average points (Validity: 70.3%)
Player default_09_gemma | Round 2: 0.59 average points (Validity: 73.4%)
Player default_09_gemma | Round 3: 0.56 average points (Validity: 76.6%)
Player default_09_gemma | Round 4: 0.50 average points (Validity: 75.0%)
Player default_09_gemma | Round 5: 0.53 average points (Validity: 73.4%)
Player default_09_llama | Round 1: 0.59 average points (Validity: 75.0%)
Player default_09_llama | Round 2: 0.62 average points (Validity: 76.6%)
Player default_09_llama | Round 3: 0.59 average points (Validity: 79.7%)
Player default_09_llama | Round 4: 0.59 average points (Validity: 84.4%)
Player default_09_llama | Round 5: 0.56 average points (Validity: 76.6%)

Top 3 Hardest Categories (Lowest Score):
Letter X - Brands: 0.00 average points (Validity: 100.0%)
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)
Letter E - Sports: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 1.00 average points (Validity: 100.0%)
Letter D - Plants: 1.00 average points (Validity: 100.0%)
Letter O - Companies: 1.00 average points (Validity: 100.0%)

`qwen2.5:7b` vs. `llama3.2:3b` vs. `gemma2:2b` at Temperature = 2.0

In [189]:
# Read in CSV files for judged cross-play at temperature=2.0
df_judged_cross_qwen_vs_llama_opt = pd.read_csv("part3_judged_outputs/judged_cross_qwen_vs_llama_opt_20.csv")
df_judged_cross_qwen_vs_gemma_opt = pd.read_csv("part3_judged_outputs/judged_cross_qwen_vs_gemma_opt_20.csv")
df_judged_cross_llama_vs_gemma_opt = pd.read_csv("part3_judged_outputs/judged_cross_llama_vs_gemma_opt_20.csv")

# Analyze the games from cross-play at temperature=2.0
analyze_crossplay(df_judged_cross_qwen_vs_llama_opt, "Qwen vs Llama (original prompt, temperature=2.0)")
analyze_crossplay(df_judged_cross_qwen_vs_gemma_opt, "Qwen vs Gemma (original prompt, temperature=2.0)")
analyze_crossplay(df_judged_cross_llama_vs_gemma_opt, "Llama vs Gemma (original prompt, temperature=2.0)")

OVERALL OUTCOMES: Qwen vs Llama (original prompt, temperature=2.0)
Overall Validity Rate: 78.4%
Overall Average Score per Player: 57.5% points per answer

Per-Model Breakdown:
Player opt_20_llama: 0.59 average points (Validity: 79.7%)
Player opt_20_qwen: 0.56 average points (Validity: 77.2%)
Player opt_20_llama | Round 1: 0.70 average points (Validity: 84.4%)
Player opt_20_llama | Round 2: 0.62 average points (Validity: 81.2%)
Player opt_20_llama | Round 3: 0.58 average points (Validity: 79.7%)
Player opt_20_llama | Round 4: 0.55 average points (Validity: 78.1%)
Player opt_20_llama | Round 5: 0.48 average points (Validity: 75.0%)
Player opt_20_qwen | Round 1: 0.56 average points (Validity: 70.3%)
Player opt_20_qwen | Round 2: 0.66 average points (Validity: 84.4%)
Player opt_20_qwen | Round 3: 0.56 average points (Validity: 78.1%)
Player opt_20_qwen | Round 4: 0.50 average points (Validity: 73.4%)
Player opt_20_qwen | Round 5: 0.53 average points (Validity: 79.7%)

Top 3 Hardest Categories (Lowest Score):
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)
Letter Z - Animals: 0.00 average points (Validity: 100.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 1.00 average points (Validity: 100.0%)
Letter G - Foods: 1.00 average points (Validity: 100.0%)
Letter C - Board games: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Qwen vs Gemma (original prompt, temperature=2.0)
Overall Validity Rate: 74.7%
Overall Average Score per Player: 60.6% points per answer

Per-Model Breakdown:
Player opt_20_gemma: 0.58 average points (Validity: 72.2%)
Player opt_20_qwen: 0.63 average points (Validity: 77.2%)
Player opt_20_gemma | Round 1: 0.59 average points (Validity: 73.4%)
Player opt_20_gemma | Round 2: 0.58 average points (Validity: 71.9%)
Player opt_20_gemma | Round 3: 0.59 average points (Validity: 75.0%)
Player opt_20_gemma | Round 4: 0.58 average points (Validity: 70.3%)
Player opt_20_gemma | Round 5: 0.56 average points (Validity: 70.3%)
Player opt_20_qwen | Round 1: 0.59 average points (Validity: 73.4%)
Player opt_20_qwen | Round 2: 0.66 average points (Validity: 79.7%)
Player opt_20_qwen | Round 3: 0.58 average points (Validity: 73.4%)
Player opt_20_qwen | Round 4: 0.64 average points (Validity: 76.6%)
Player opt_20_qwen | Round 5: 0.69 average points (Validity: 82.8%)

Top 3 Hardest Categories (Lowest Score):
Letter E - Sports: 0.00 average points (Validity: 100.0%)
Letter Z - Animals: 0.00 average points (Validity: 100.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 1.00 average points (Validity: 100.0%)
Letter K - Cities: 1.00 average points (Validity: 100.0%)
Letter M - Languages: 1.00 average points (Validity: 100.0%)

OVERALL OUTCOMES: Llama vs Gemma (original prompt, temperature=2.0)
Overall Validity Rate: 75.8%
Overall Average Score per Player: 57.7% points per answer

Per-Model Breakdown:
Player opt_20_gemma: 0.53 average points (Validity: 71.6%)
Player opt_20_llama: 0.62 average points (Validity: 80.0%)
Player opt_20_gemma | Round 1: 0.53 average points (Validity: 70.3%)
Player opt_20_gemma | Round 2: 0.50 average points (Validity: 70.3%)
Player opt_20_gemma | Round 3: 0.55 average points (Validity: 75.0%)
Player opt_20_gemma | Round 4: 0.47 average points (Validity: 67.2%)
Player opt_20_gemma | Round 5: 0.62 average points (Validity: 75.0%)
Player opt_20_llama | Round 1: 0.67 average points (Validity: 84.4%)
Player opt_20_llama | Round 2: 0.61 average points (Validity: 81.2%)
Player opt_20_llama | Round 3: 0.58 average points (Validity: 78.1%)
Player opt_20_llama | Round 4: 0.59 average points (Validity: 79.7%)
Player opt_20_llama | Round 5: 0.64 average points (Validity: 76.6%)

Top 3 Hardest Categories (Lowest Score):
Letter H - Things at the beach: 0.00 average points (Validity: 20.0%)
Letter G - U.S. states: 0.00 average points (Validity: 100.0%)
Letter Z - Animals: 0.00 average points (Validity: 100.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 1.00 average points (Validity: 100.0%)
Letter W - Things in a park: 1.00 average points (Validity: 100.0%)
Letter A - Jobs: 1.00 average points (Validity: 100.0%)

`qwen2.5:7b` vs. `llama3.2:3b` vs. `gemma2:2b` at Using the Obscure Prompt (Temperature = 2.0)

In [190]:
# Read in CSV files for judged cross-play using the obscure prompt 
# (temperature=2.0)
df_judged_cross_qwen_vs_llama_obscure = pd.read_csv("part3_judged_outputs/judged_cross_qwen_vs_llama_obscure_20.csv")
df_judged_cross_qwen_vs_gemma_obscure = pd.read_csv("part3_judged_outputs/judged_cross_qwen_vs_gemma_obscure_20.csv")
df_judged_cross_llama_vs_gemma_obscure = pd.read_csv("part3_judged_outputs/judged_cross_llama_vs_gemma_obscure_20.csv")

# Analyze the games from cross-play using the obscure prompt
analyze_crossplay(df_judged_cross_qwen_vs_llama_obscure, "Qwen vs Llama (obscure prompt, temperature=2.0)")
analyze_crossplay(df_judged_cross_qwen_vs_gemma_obscure, "Qwen vs Gemma (obscure prompt, temperature=2.0)")
analyze_crossplay(df_judged_cross_llama_vs_gemma_obscure, "Llama vs Gemma (obscure prompt, temperature=2.0)")

OVERALL OUTCOMES: Qwen vs Llama (obscure prompt, temperature=2.0)
Overall Validity Rate: 35.6%
Overall Average Score per Player: 34.4% points per answer

Per-Model Breakdown:
Player obscure_20_llama: 0.36 average points (Validity: 37.2%)
Player obscure_20_qwen: 0.33 average points (Validity: 34.1%)
Player obscure_20_llama | Round 1: 0.45 average points (Validity: 46.9%)
Player obscure_20_llama | Round 2: 0.34 average points (Validity: 35.9%)
Player obscure_20_llama | Round 3: 0.27 average points (Validity: 29.7%)
Player obscure_20_llama | Round 4: 0.38 average points (Validity: 37.5%)
Player obscure_20_llama | Round 5: 0.36 average points (Validity: 35.9%)
Player obscure_20_qwen | Round 1: 0.36 average points (Validity: 37.5%)
Player obscure_20_qwen | Round 2: 0.33 average points (Validity: 34.4%)
Player obscure_20_qwen | Round 3: 0.30 average points (Validity: 32.8%)
Player obscure_20_qwen | Round 4: 0.34 average points (Validity: 34.4%)
Player obscure_20_qwen | Round 5: 0.31 average points (Validity: 31.2%)

Top 3 Hardest Categories (Lowest Score):
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)
Letter E - Sports: 0.00 average points (Validity: 0.0%)
Letter L - Things in a library: 0.10 average points (Validity: 10.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 0.90 average points (Validity: 90.0%)
Letter Y - Foods: 0.90 average points (Validity: 90.0%)
Letter X - Words in English: 0.90 average points (Validity: 90.0%)

OVERALL OUTCOMES: Qwen vs Gemma (obscure prompt, temperature=2.0)
Overall Validity Rate: 32.7%
Overall Average Score per Player: 31.4% points per answer

Per-Model Breakdown:
Player obscure_20_gemma: 0.31 average points (Validity: 32.5%)
Player obscure_20_qwen: 0.32 average points (Validity: 32.8%)
Player obscure_20_gemma | Round 1: 0.23 average points (Validity: 25.0%)
Player obscure_20_gemma | Round 2: 0.23 average points (Validity: 25.0%)
Player obscure_20_gemma | Round 3: 0.39 average points (Validity: 40.6%)
Player obscure_20_gemma | Round 4: 0.39 average points (Validity: 39.1%)
Player obscure_20_gemma | Round 5: 0.31 average points (Validity: 32.8%)
Player obscure_20_qwen | Round 1: 0.34 average points (Validity: 35.9%)
Player obscure_20_qwen | Round 2: 0.33 average points (Validity: 34.4%)
Player obscure_20_qwen | Round 3: 0.28 average points (Validity: 29.7%)
Player obscure_20_qwen | Round 4: 0.33 average points (Validity: 32.8%)
Player obscure_20_qwen | Round 5: 0.30 average points (Validity: 31.2%)

Top 3 Hardest Categories (Lowest Score):
Letter F - Things in a backpack: 0.00 average points (Validity: 0.0%)
Letter M - Clothing items: 0.00 average points (Validity: 0.0%)
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter Y - Foods: 1.00 average points (Validity: 100.0%)
Letter Q - Words in English: 0.80 average points (Validity: 80.0%)
Letter X - Words in English: 0.80 average points (Validity: 80.0%)

OVERALL OUTCOMES: Llama vs Gemma (obscure prompt, temperature=2.0)
Overall Validity Rate: 35.5%
Overall Average Score per Player: 34.8% points per answer

Per-Model Breakdown:
Player obscure_20_gemma: 0.32 average points (Validity: 32.5%)
Player obscure_20_llama: 0.38 average points (Validity: 38.4%)
Player obscure_20_gemma | Round 1: 0.27 average points (Validity: 28.1%)
Player obscure_20_gemma | Round 2: 0.23 average points (Validity: 23.4%)
Player obscure_20_gemma | Round 3: 0.42 average points (Validity: 42.2%)
Player obscure_20_gemma | Round 4: 0.38 average points (Validity: 37.5%)
Player obscure_20_gemma | Round 5: 0.30 average points (Validity: 31.2%)
Player obscure_20_llama | Round 1: 0.47 average points (Validity: 48.4%)
Player obscure_20_llama | Round 2: 0.41 average points (Validity: 40.6%)
Player obscure_20_llama | Round 3: 0.30 average points (Validity: 29.7%)
Player obscure_20_llama | Round 4: 0.38 average points (Validity: 37.5%)
Player obscure_20_llama | Round 5: 0.34 average points (Validity: 35.9%)

Top 3 Hardest Categories (Lowest Score):
Letter S - Things in an office: 0.00 average points (Validity: 0.0%)
Letter E - Companies: 0.00 average points (Validity: 0.0%)
Letter Y - Things at a party: 0.00 average points (Validity: 0.0%)

Top 3 Easiest Categories (Highest Score):
Letter Q - Words in English: 0.90 average points (Validity: 90.0%)
Letter D - Musical instruments: 0.90 average points (Validity: 90.0%)
Letter Y - Foods: 0.90 average points (Validity: 90.0%)